config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/leaderboard', to: 'static_pages#leaderboard', via: 'get'  
  match '/give_feedback', to: 'feedbacks#give_feedback', via: 'get'
  match 'feedbacks/complete/:id', to: 'feedbacks#complete', via: 'post' 
  match '/myfeedback', to: 'users#myfeedback',  via: 'get'
  match '/crunchdata', to: 'users#crunchdata', via: 'get'

  get "static_pages/home"  
  get "static_pages/help"
  get "static_pages/about" 
  get "static_pages/contact" 

 

  

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :microposts, dependent: :destroy
    has_many :relationships, foreign_key: "follower_id", dependent: :destroy
    has_many :followed_users, through: :relationships, source: :followed 
    has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
    has_many :followers, through: :reverse_relationships, source: :follower
  	before_save { self.email = email.downcase } # 
  	before_create :create_remember_token

  	#??
  	#before_save { email.downcase! } # putting this in or out changes the errors ??# { self.email = email.downcase } 
  	#
	validates :name, presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	#has_secure_password 
  	#validates :password, length: { minimum: 6 }

  	def User.new_remember_token
      SecureRandom.urlsafe_base64
    end

    def User.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
    end

    def feed
      Micropost.from_users_followed_by(self)
    end

    def following?(other_user)
      relationships.find_by(followed_id: other_user.id)
    end

    def follow!(other_user)
      relationships.create!(followed_id: other_user.id)
    end

    def unfollow!(other_user)
      relationships.find_by(followed_id: other_user.id).destroy!
    end

    private

      def create_remember_token
        self.remember_token = User.encrypt(User.new_remember_token)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  # before_action :admin_user,     only: [:destroy, :admin_user]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App"
      redirect_to @user   # redirects to user show page (which is what?)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User delted."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  #def give_feedback
  #end

  def feedback
  end

  def crunchdata
    null_array = Array.new(Attribute.count){ 0 } 
       all_feedback = Feedback.all 
       all_feedback.find(2).to_id  # just for debug 

      all_feedback.each do |vote| 

         @user = User.find(vote.to_id) 
         @user.name # remove - for debug 

         @user.ratings ||= null_array 
        # @user.ratings 
         @user.ratings[vote.attribute_id] = 17 # maybe I can't do it by modifying user 
         @user.ratings[3]  
         if @user.save   # user.save! and look for errors 
          render 'homepage' #"saved" 
         else 
          render 'show_follow' #"didn't save" 
         end 
         #{}User.find(vote.to_id).ratings[vote.attribute_id]+=1 
      end
  end




private

  	def user_params
      # add admin per Exercise 9.6.1
  		params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  	end

    # Before filters

    ### re 10.3, move signed_in_user to the Sessions helper so that Microposts controller can use it also
    # def signed_in_user
    #   unless signed_in?
    #     store_location
    #     redirect_to signin_url, notice: "Please sign in."
    #   end
    # end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = {size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_chart1.html.erb
  <!--Load the AJAX API-->
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">

    // Load the Visualization API and the piechart package.
    google.load('visualization', '1.0', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {

      // Create the data table.
      var data1 = new google.visualization.DataTable();
      data1.addColumn('string', 'Aspect');
      data1.addColumn('number', 'Rating');
      data1.addRows([
        ['Strategy', 7.2],
        ['Execution', 5.5],

      ]);

      // Set chart options  <%# most I can't get to work %>
      var options = {'title':'Factory cost reduction',
                     width:450,
                     height:180,
                     vAxis: { textStyle:{fontSize:15}},
                     legend: { position:'none' },
					 titleTextStyle:{fontSize:20},
					 

					 hAxis: { ticks: [6,7] },
                     hAxis: { minValue: 0 }, 

                     hAxis: { titleTextStyle:{fontSize:25}}

                     };

      // Instantiate and draw our chart, passing in some options.
      var chart1 = new google.visualization.BarChart(document.getElementById('chart1_div'));
      chart1.draw(data1, options);
    }
  </script>

  <div id="chart1_div"></div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
<%# the remote: true means it does it with Ajax so that a request can be sent to the server without leaving the page %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_homepage.html.erb
<!doctype html>

<html>
  
  <head>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

  </head>
  
  <body>

   
    <br>
    <div class="container">
      <div class="row">
        <%= render "users/signed_in_sidebar" %>
        
        <div class="col-md-7">

          <div class="well well-sm">
            <%# columns[1]=Feedback.find_by(to_id:"1").attribute_id %>
            <%= render "users/chart1" %>
          </div>
          <div class="well well-sm">
            <h4>Competitor acquisition</h4>
            <div class="row">
              <div class="col-md-5" align="right">
                <p>Strategy</p>
                <p>Execution</p>
              </div>
              <div class="col-md-6">
                <div class="progress">
                  <div class="progress-bar" style="width: 80%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 20%;"></div>
                </div>
              </div>
            </div>
          </div>

          <!-- this is the main section -->
          <div class="well well-sm">
          <% user = User.find_by(id: "17") %>  <!-- random for now, select by recent or other later -->
          <p><%= user.name + " | " + user.email %> </p>
          <%#= link_to user.name,  + " | " + user.email %>
          <%#= link_to current_user.name, "give_feedback"  %> <%# goes to users/show.html.erb %>

            <div class="row">
              <div class="col-md-5" align="right">
                <p>Ambitious</p>
                <p>Lead by example</p>
                <p>Great with customers</p>
                <p>Married to the job</p>
                <p>Big picture thinker</p>
                <p>Reliable</p>
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" style="width: 30%;"></div>
                </div>
              </div>
              <div class="col-md-5">
                <div class="progress">
                  <div class="progress-bar" style="width: 80%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 60%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 30%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 20%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 20%;"></div>
                </div>
                <p>Needs to improve hiring</p>
              </div>
            </div>
          </div>
          <div class="well well-sm">
            <% user = User.find_by(id: "25") %>  
            <p><%= user.name + " | " + user.email %> </p>
            <div class="row">
              <div class="col-md-5" align="right">
                <p>Big picture thinker</p>
                <p>Reliable</p>
                <p>In early / stays late</p>
                <p>Leads by example</p>
                <p>Leadership</p>
                <p>Technical skills</p>
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" style="width: 30%;"></div>
                </div>
              </div>
              <div class="col-md-5">
                <div class="progress">
                  <div class="progress-bar" style="width: 60%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 50%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 40%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 10%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 10%;"></div>
                </div>
                <p>Needs to complete work more quickly</p>
              </div>
            </div>
          </div>
          <div class="well well-sm">
            <% user = User.find_by(id: "20") %>  
            <p><%= user.name + " | " + user.email %> </p>
            <div class="row">
              <div class="col-md-5" align="right">
                <p>Knows the market</p>
                <p>Ambitious</p>
                <p>Rainmaker</p>
                <p>Team player</p>
                <p>Dependable</p>
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" style="width: 30%;"></div>
                </div>
              </div>
              <div class="col-md-5">
                <div class="progress">
                  <div class="progress-bar" style="width: 60%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 50%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 40%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 10%;"></div>
                </div>
                <p>Needs to build better rapport</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <hr>

    </div>
    <!-- /container -->
  </body>




</html>

app/views/users/_signed_in_scaffold.html.erb
    <div class="col-md-5">
      <div class="well well-sm" <!-- this is the sidebar -->
        <div class="well well-sm">
          <%# was @user.name, @user.email but that was nil %>
          <%= current_user.name %>, <%= current_user.email %>
          <p>Feedback for me</p>
          <p>+1 Above and beyond</p>
        </div>
        <div class="well well-sm">
          <p>Search Projects or Coworkers</p>
          <input type="text" class="form-control">
          <p></p>
          <a class="btn btn-primary btn-sm">Search</a>
        </div>
        <div class="well well-sm">Company Leaderboard
        </div>
        <div class="well well-sm">
          <p>Company Lookup</p>
          <input type="text" class="form-control">
          <p>Trending:</p>
          <ul>
            <li>Facebook</li>
            <li>Exxon Mobil</li>
            <li>Qualcomm</li>
          </ul>
        </div>
      </div>
    </div>

app/views/users/_signed_in_sidebar.html.erb
    <div class="col-md-5">
      <div class="well well-sm" <!-- this is the sidebar -->
        <div class="well well-sm">
          <%# was @user.name, @user.email but that was nil %>
          <h4><%= current_user.name %>, <%= current_user.email %></h4>
          <p> <%= link_to "View Detailed Feedback", myfeedback_path(current_user) %> </p> <%# I didn't need to define a myfeedback_path - it just went to users/myfeedback.html.erb %>
          <%# an example of going to a secure page= link_to "Settings", edit_user_path(current_user) %>
          <p>+1 Above and beyond</p>
        </div>
        <div class="well well-sm">
          <p>Search Projects or Coworkers</p>
          <input type="text" class="form-control">
          <p></p>
          <a class="btn btn-primary btn-sm">Search</a>
        </div>
        <div class="well well-sm">
        <%= link_to "Company Leaderboard", '/leaderboard' %> 
        </div>
        <div class="well well-sm">
          <p>Company Lookup</p>
          <input type="text" class="form-control">
          <p>Trending:</p>
          <ul>
            <li>Facebook</li>
            <li>Exxon Mobil</li>
            <li>Qualcomm</li>
          </ul>
        </div>
      </div>
    </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  	  <%= link_to "delete", user, method: :delete, data: { confirm: "you sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %> 

<ul class="users"> <%# makes it render _user.html.erb and the next line passes the user%>
	<%= render @users %>
</ul>

<%= will_paginate %> 

app/views/users/myfeedback.html.erb
<%# provide(:title, @user.name) # why did this not get @user.  When this code was in show.html.erb, it had @user ? %> 
<%# maybe OK that I put current_user every palce that @user was - to start, we only want to show this for current_user.  Down the road, once your boss has access, that will change %>
<% provide(:title, current_user.name) %>

      <br>
    <div class="container">
      <div class="row">
      <!-- this is the sidebar.  Remember to put the co. strategy ratings back in.  -->
        <%= render "users/signed_in_sidebar" %>        
        <div class="col-md-7">
          <!-- this is the main section -->
          <div class="well well-sm">
            <p></p>
            <h4><%= current_user.name %>, <%= current_user.email %></h4>


            <p></p>
            <div class="row">
              <div class="col-md-5" align="right">
                <p>Ambitious</p>
                <p>Lead by example</p>
                <p>Great with customers</p>
                <p>Married to the job</p>
                <p>Big picture thinker</p>
                <p>Reliable</p><br>
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" style="width: 50%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" style="width: 40%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" style="width: 30%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" style="width: 10%;"></div>
                </div>
              </div>
              <div class="col-md-5">
                <div class="progress">
                  <div class="progress-bar" style="width: 80%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 60%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 30%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 20%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 20%;"></div>
                </div>
                <p>Needs to better market understanding</p>
                <p>Needs a role with better fit</p>
                <p>Needs to give credit where due</p>
                <p>Needs to not rest on laurels</p>
                <p>Needs better follow up on actions</p>
              </div>
            </div>
          </div>
          <div class="well well-sm">
          <h4>Job performance based on 7 reviewers</h4>
            <div class="row">
              <div class="col-md-5" align="right">
              <font size="4">
                <p>Results</p>
                <p></p>
                <p>Job Knowledge</p>
                <p></p>
                <p>Initiative</p>
                <p></p>
                <p>Communication</p>
                <p></p>
                <p>Leadership</p>
              </font>
              </div>
              <div class="col-md-5">
                <div class="progress">
                  <div class="progress-bar" style="width: 60%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 50%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 40%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 10%;"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar" style="width: 10%;"></div>
                </div>
              </div>
            </div>
          </div>
        </div>

<!--   <div class="span8">
    <%#= render 'follow_form' if signed_in? %>
    <%# if @user.microposts.any? %>
      <h3>Microposts (<%#= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%#= render @microposts %>
      </ol>
      <%#= will_paginate @microposts %>
    <%# end %>
  </div> -->

      </div>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label "Work email address" %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<br>
<div class="container">
  <div class="row">
    <%= render "users/signed_in_sidebar" %>
    <div class="col-md-7">
      <!-- this is the main section -->
      <div class="well well-sm">
        <p></p>
    
        <h4>Give feedback for <%= @user.name %></h4>

        <div class="row">
          <div class="col-md-5" align="left">
            <p>Let your coworker know how he or she is doing in these five key areas. </p>
            <p></p>
            <p>10 is Best</p>
            <p></p>
            <p>1 is Worst</p>
            <p></p>
            <p>0 means "no rating given"</p>

          </div>
          <div class="col-md-5">
          Results: <span id="resultsRange">0</span>
          <input type="range" min="0" max="10" value="0" step="1" onchange="resultsValue(this.value)" />
          Job Knowledge: <span id="jkRange">0</span>
          <input type="range" min="0" max="10" value="0" step="1" onchange="jkValue(this.value)" />
          Initiative: <span id="initiativeRange">0</span>
          <input type="range" min="0" max="10" value="0" step="1" onchange="initiativeValue(this.value)" />          
          Communication: <span id="commRange">0</span>
          <input type="range" min="0" max="10" value="0" step="1" onchange="commValue(this.value)" />          
          Leadership: <span id="leadershipRange">0</span>
          <input type="range" min="0" max="10" value="0" step="1" onchange="leadershipValue(this.value)" />          

          <script type="text/javascript">
          function resultsValue(newValue)
          {
            document.getElementById("resultsRange").innerHTML=newValue;
          }
          function jkValue(newValue)
          {
            document.getElementById("jkRange").innerHTML=newValue;
          }
          function initiativeValue(newValue)
          {
            document.getElementById("initiativeRange").innerHTML=newValue;
          }
          function commValue(newValue)
          {
            document.getElementById("commRange").innerHTML=newValue;
          }
          function leadershipValue(newValue)
          {
            document.getElementById("leadershipRange").innerHTML=newValue;
          }
          </script>

            
          </div>
        </div>
      </div>
      <div class="well well-sm">
        <p></p>

        <h4>Select attributes that apply to <%= @user.name %> </h4>Select as many or as few as you wish to describe <%= @user.name%>'s job performance

          <% all_attributes = Attribute.all %>

          <%= form_tag("/feedbacks/complete/"+params[:id],  :method => "post", :remote => true) do %> <%# from codelearn.org %>
          
          <% all_attributes.each do |attribute| %> 
            <% if attribute.good == 'true' %>
              <div class="col-md-6" >
                <label>
                  <%= check_box_tag  ("attribute_checkbox[]"),attribute.id %><%=  attribute.attribute_name %> 
                </label> 
              </div>  
              <div class="col-md-6">
                <label>
                  <%= check_box_tag  ("attribute_checkbox[]"),attribute.opposite_id %><%=  all_attributes.find(attribute.opposite_id).attribute_name%>
                </label>
              </div>  
            <% end %>  

          <%end%>
          
          <%= submit_tag("Submit feedback", :class=>"btn btn-success") %>
          <%end %>

        
      </div> 
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>