config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/leaderboard', to: 'static_pages#leaderboard', via: 'get'  
  match '/give_feedback', to: 'feedbacks#give_feedback', via: 'get'
  match 'feedbacks/complete/:id', to: 'feedbacks#complete', via: 'post' 
  match '/myfeedback', to: 'users#myfeedback',  via: 'get'
  match '/crunchdata', to: 'users#crunchdata', via: 'get'

  get "static_pages/home"  
  get "static_pages/help"
  get "static_pages/about" 
  get "static_pages/contact" 

 

  

end

app/views/shared/_delete_item.html.erb
<!-- not working -->

<% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
  	<%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= wrap(feed_item.content) %></span> 
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  
  <!-- <%= render partial: 'shared/delete_item', collection: feed_item%> -->

  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_landing.html.erb
<!doctype html>

<html>
  
  <head>

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">


  </head>
  
  <body>


    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="media">
            <a class="pull-left" href="#"></a>
            <div class="media-body">
              <p><!--StartFragment--></p>
              <p></p>
              <!--EndFragment-->
              <well>
                <form>
                  <div class="form-group">
                    <div class="controls"></div>
                  </div>
                  <div class="form-group"></div>
                  <div class="row">
                    <div class="col-md-5">
                      <img src="http://i.imgur.com/0Pua12E.png" width="250">
                      <h3 class="media-heading">Transparency made easy</h3>
                    </div>
                    <div class="col-md-7">
                      <label class="control-label">Join your company's feedback network anonymously and for free</label>
                      <div class="form-group">
                        <div class="well well-sm">
<!--                           <label class="control-label">Enter your work email address:</label>

                      

                        <form action="demo_form.asp">
                          <input type="text" name="email_landing" ><br>
                          <input type="submit" value="Submit xx">
                          </form>

                        <form accept-charset="UTF-8" action="/users" class="yj-clearfix" id="new_user" method="post" novalidate="novalidate"><div style="margin:0;padding:0;display:inline"><input name="utf8" /></div>        <input class="signup-email-textbox water-marked" id="user_email" name="user[email]" size="30" title="Enter your work email address" type="email" />
        <button id="new_user_submit" type="submit" class="yj-btn yj-btn-orangey">Sign up</button>
</form>   -->

                          <p>Only employees with a verified company email can join your company's network</p>
                          <%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %> <%# from Hartl code %>
                        </div>
                      </div>
                    </div>
                  </div>
                </form>
              </well>
            </div>
            <section>
              <div class="well well-sm">
                <div class="row">
                  <div class="col-md-3">
                    <p><b></b></p>
                    <h3><b>Beth</b></h3>
                    <p></p>
                    <p>GE Capital</p>
                    <p>Customer relations</p>
                    <p></p>
                  </div>
                  <div class="col-md-2" align="right">
                    <p>Ambitious</p>
                    <p>Leads by example</p>
                    <p>Reliable</p>
                  </div>
                  <div class="col-md-3">
                    <div class="progress">
                      <div class="progress-bar" style="width: 80%;"></div>
                    </div>
                    <div class="progress">
                      <div class="progress-bar" style="width: 60%;"></div>
                    </div>
                    <div class="progress">
                      <div class="progress-bar" style="width: 50%;"></div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section>
              <div class="well well-sm">
                <div class="row">
                  <div class="col-md-3">
                    <p><b></b></p>
                    <h3><b>Bill</b></h3>
                    <p></p>
                    <p>Deloitte</p>
                    <p>Analyst</p>
                    <p></p>
                  </div>
                  <div class="col-md-2" align="right">
                    <p>Above and beyond</p>
                    <p>Finds a way to win</p>
                    <p>Leadership</p>
                  </div>
                  <div class="col-md-3">
                    <div class="progress">
                      <div class="progress-bar" style="width: 90%;"></div>
                    </div>
                    <div class="progress">
                      <div class="progress-bar" style="width: 50%;"></div>
                    </div>
                    <div class="progress">
                      <div class="progress-bar" style="width: 30%;"></div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
        <div class="col-lg-4">
          <h2>How BumptUp works</h2>
          <p>BumptUp verifies that you are an employee of your company through your work email address. After that, you can give your company the feedback it needs about its direction and its employees. All of your actions on BumptUp are private. No one else even knows you use the system if you don't let them know.</p>
          <p><a class="btn btn-default" href="#">More &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2>How BumptUp helps</h2>
          <p>Your company needs real, honest, real time feedback from the people who know best: you and your coworkers. While it's easy enough to give praise, it is more difficult to give constructive feedback about what needs to improve. Yet, constructive feedback is what helps your company the most and what your coworkers yearn for. BumptUp tears down the barriers to providing this feedback with a system that allows the feedback to come from anonymized sources within the organization.</p>
          <p><a class="btn btn-default" href="#">More &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2>How BumptUp is better</h2>
          <p>"<span style="font-family: Helvetica, Arial, sans-serif; font-size: 15px;">Most employee engagement or satisfaction surveys are a stupendous waste of money and time. Everyone in the organization dreads them and little or nothing ever happens to the feedback." - Bernard Marr</span></p>
          <p>BumptUp is <b><i>pushed</i></b> by employees rather than <b><i>pulled</i></b> by HR or senior management. &nbsp;It is quick, safe, and gets honest feedback.</p>
          <p><a class="btn btn-default" href="#">More &raquo;</a></p>
        </div>
      </div>
      <hr>
      <footer>
        <p>&copy; BumptUp 2014</p>
      </footer>
    </div>
    <!-- /container -->
  </body>

</html>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
#### IS THIS STILL USED ?? ######
<h4>
  <%= link_to current_user.name, current_user %> <%# goes to users/show.html.erb %>
  <%#= link_to current_user.name, "/users/show" %> <%# goes to users/show.html.erb %>
</h4>
<span>
  <%= pluralize(current_user.microposts.count, "piece")%> of feedback received
</span>